`try`, `catch`, `throw`

# 1. `throw`
程序通过throw抛出异常
# 2. `catch`
在想要处理问题的地方，通过异常处理程序捕获异常。
# 3. `try`
try块中的代码会标识 将被激活的 特定异常。通常后面跟着一个或多个catch块。

# 4. e.g.

```cpp
try
{
    //code lines
    // 在某个子函数中可能出现代码：
    throw "error exist!";
} catch (ExpectionName e1) {

} catch (ExpectionName e2) {

} catch (const char* msg) {
    ceer << msg << endl;
} 

```